### ISSUE TITLE
support for more testnets, like sepolia, etc

### ISSUE THREAD

**Issue by jafar75** [circlefin/evm-cctp-contracts#13]
Hi there, 
As we know that goerli ethereum testnet is deprecated and also tx fees are high in that network, I want to know when will be CCTP deployed on Sepolia testnet?

**Comment by walkerq** [comment]
The contracts are now deployed on Sepolia chains, see addresses [here](https://developers.circle.com/stablecoins/docs/evm-smart-contracts#testnet-contract-addresses).
