### ISSUE TITLE
Add ABI for Contracts by Contract Address

### ISSUE THREAD

**Issue by kalnun** [circlefin/evm-cctp-contracts#31]
Please upload  the ABI for the Smart Contracts with the Contract Address by Blockchain.

**Comment by walkerq** [comment]
ABIs: https://github.com/circlefin/evm-cctp-contracts/tree/1662356f9e60bb3f18cb6d09f95f628f0cc3637f/docs/abis/cctp
Addresses: https://developers.circle.com/stablecoins/docs/evm-smart-contracts#mainnet-contract-addresses
