### ISSUE TITLE
Registering a new _domain

### ISSUE THREAD

**Issue by lcswillems** [circlefin/evm-cctp-contracts#9]
Hello,

I have read the whole documentation, smart contracts code and interaction code. I am very impressed by the solution that is being built. Circle is going to significantly improve stablecoin access on blockchains and increase the strengh of USDC.

From my understanding, if a Blockchain wants to start integrating the **devnet** mint/burn bridge of Circle, it needs a few actions from Circle:

- for integrating the Ethereum -> Blockchain devnet bridge, the Blockchain needs to be associated a `_domain` in the `remoteTokenMessengers` storage of `TokenMessenger.sol`,

- for integrating the Blockchain -> Ethereum devnet bridge, the Blockchain needs either that Circle attesters work with the Blockchain or that Circle whitelists the attesters made by the Blockchain, in the `enabledAttesters` storage of `MessageTransmitter.sol`.

How to register a new `_domain` in the `remoteTokenMessengers` storage of `TokenMessenger.sol`? This way, the Blockchain could already start the integration of the Ethereum -> Blockchain devnet bridge.

**Comment by walkerq** [comment]
Hi @lcswillems,

Your assessment is correct. For the time being, we aren't registering new domains in Circle-deployed CCTP contracts, or attesting to new domains in Circle's attester. But, more domains will be added over time. You can certainly deploy the contracts yourself, and run your own attester. We hope to eventually make this process easier. Thanks!
